version: '3.8'

services:
  bot:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm start

  mongodb:
    ports:
      - "27017:27017"

  lavalink:
    ports:
      - "2333:2333"