version: '3.8'

services:
  musicbot:
    image: karutoil/deepquasar-multifunctionalbot:latest
    container_name: musicbot-container
    env_file: .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
