version: '3.8'

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: deepquasar-lavalink
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD:-youshallnotpass}
      - YOUTUBE_REFRESH_TOKEN=${YOUTUBE_REFRESH_TOKEN}
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      - ./lavalink/plugins:/opt/Lavalink/plugins
    restart: unless-stopped
    networks:
      - bot_network

  mongodb:
    image: mongo:6
    container_name: deepquasar-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=musicbot
    volumes:
      - mongodb_data:/data/db
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  mongodb_data: