version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb-container-2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=musicbot
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - musicnet

networks:
  musicnet:
    driver: bridge

volumes:
  mongodb_data: