server:
  port: 2333
  address: 0.0.0.0
  password: ${LAVALINK_PASSWORD}
  sources:
    youtube: false  # Disable deprecated built-in YouTube extractor
    bandcamp: true
    soundcloud: true
    twitch: true
    vimeo: true
    nico: true
    http: false     # Disable unless you need to play arbitrary HTTP URLs
    local: false    # Disable unless you want local file playback

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.2"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.5.0"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  server:
    password: "${LAVALINK_PASSWORD}"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: false
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    nonAllocatingFrameBuffer: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 25
    youtubeSearchEnabled: true
    playerUpdateInterval: 5
    soundcloudSearchEnabled: true
    gc-warnings: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    oauth:
      enabled: true
      refreshToken: "${YOUTUBE_REFRESH_TOKEN}"
    clients:
      - TV
      - TVHTML5EMBEDDED
      - WEB
      - MWEB
      - WEBEMBEDDED
      - MUSIC
      - ANDROID_VR
      - ANDROID_MUSIC
      - IOS
    clientOptions:
      TV:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: false
      TVHTML5EMBEDDED:
        playback: true
        playlistLoading: false
        searching: true
        videoLoading: true
      WEB:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      MWEB:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      WEBEMBEDDED:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: true
      MUSIC:
        playback: false
        playlistLoading: false
        searching: true
        videoLoading: false
      ANDROID_VR:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      ANDROID_MUSIC:
        playback: true
        playlistLoading: false
        searching: true
        videoLoading: true
      IOS:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true

logging:
  file:
    max-history: 7
    max-size: 10MB
  level:
    root: INFO
    lavalink: INFO
    lavalink.server.io.SocketContext: INFO
    com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: INFO
    dev.lavalink.youtube: INFO
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true

spring:
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: ALWAYS
