name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    runs-on: [self-hosted, windows]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Start Docker Service (Windows)
        run: |
          Start-Service docker
          docker info

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true  # Ensures Buildx is properly configured

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: karutoil/deepquasar-multifunctionalbot
          tags: |
            type=raw,value=latest
            type=sha,format=short
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
