name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if only README.md changed
        id: filter
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -v '^README.md$' | grep .; then
            echo "only_readme=false" >> $GITHUB_OUTPUT
          else
            echo "only_readme=true" >> $GITHUB_OUTPUT
          fi

      - name: Log in to Docker Hub
        if: steps.filter.outputs.only_readme != 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.filter.outputs.only_readme != 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: karutoil/deepquasar-multifunctionalbot:latest

      - name: Update Docker Hub description with README.md
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          README_CONTENT=$(cat README.md | jq -Rs .)
          curl -s -X PATCH https://hub.docker.com/v2/repositories/karutoil/deepquasar-multifunctionalbot/ \
            -H "Content-Type: application/json" \
            -H "Authorization: JWT $(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"$DOCKERHUB_USERNAME\", \"password\": \"$DOCKERHUB_TOKEN\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)" \
            -d "{\"full_description\": $README_CONTENT}"
